### ISSUE TITLE
Build failing on Windows 7 

### ISSUE THREAD

**Issue by usko1** [tidepool-org/chrome-uploader#732]
Hi, i am trying to build chrome uploader on windows but without success. I have node version 10.13.0 installed. I was even not able to build it on Mac or Ubuntu with different node versions. Still get an error regardings USB. On windows machine  I get this error:

 with code 0
[0] Error: C:\Program Files\nodejs\node.exe exited with code 1
[0] Output:
[0]
[0] > usb@1.3.2 install C:\temp\chrome-uploader\app\node_modules\usb
[0] > node-pre-gyp install --fallback-to-build
[0]
[0] Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\
node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-b
uild --module=C:\temp\chrome-uploader\app\node_modules\usb\src\binding\usb_bindi
ngs.node --module_name=usb_bindings --module_path=C:\temp\chrome-uploader\app\no
de_modules\usb\src\binding --napi_version=3 --node_abi_napi=napi' (1)
[0]
[0] Error output:
[0] node-pre-gyp WARN Using request for node-pre-gyp https download
[0] node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb
/releases/download/1.3.2/usb_bindings-v1.3.2-electron-v1.8-win32-x64.tar.gz
[0] node-pre-gyp WARN Pre-built binaries not found for usb@1.3.2 and electron@1.
8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)

[0] node-pre-gyp WARN Pre-built binaries not installable for usb@1.3.2 and elect
ron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node
-gyp)
[0] node-pre-gyp WARN Hit error Connection closed while downloading tarball file

[0] Traceback (most recent call last):
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\g
yp_main.py", line 16, in <module>
[0]     sys.exit(gyp.script_main())
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\__init__.py", line 545, in script_main
[0]     return main(sys.argv[1:])
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\__init__.py", line 538, in main
[0]     return gyp_main(args)
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\__init__.py", line 523, in gyp_main
[0]     generator.GenerateOutput(flat_list, targets, data, params)
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\generator\msvs.py", line 2025, in GenerateOutput
[0]     version=msvs_version)
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\MSVSNew.py", line 213, in __init__
[0]     self.Write()
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\MSVSNew.py", line 340, in Write
[0]     f.close()
[0]   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\p
ylib\gyp\common.py", line 393, in close
[0]     os.rename(self.tmp_path, filename)
[0] WindowsError: [Error 183] Cannot create a file when that file already exists

[0] gyp ERR! configure error
[0] gyp ERR! stack Error: `gyp` failed with exit code: 1
[0] gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:345:16)
[0] gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
[0] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_pr
ocess.js:240:12)
[0] gyp ERR! System Windows_NT 6.1.7601
[0] gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\n
odejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
"--fallback-to-build" "--module=C:\\temp\\chrome-uploader\\app\\node_modules\\us
b\\src\\binding\\usb_bindings.node" "--module_name=usb_bindings" "--module_path=
C:\\temp\\chrome-uploader\\app\\node_modules\\usb\\src\\binding" "--napi_version
=3" "--node_abi_napi=napi"
[0] gyp ERR! cwd C:\temp\chrome-uploader\app\node_modules\usb
[0] gyp ERR! node -v v10.13.0
[0] gyp ERR! node-gyp -v v3.8.0
[0] gyp ERR! not ok
[0] node-pre-gyp ERR! build error
[0] node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\no
de.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-g
yp.js configure --fallback-to-build --module=C:\temp\chrome-uploader\app\node_mo
dules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path
=C:\temp\chrome-uploader\app\node_modules\usb\src\binding --napi_version=3 --nod
e_abi_napi=napi' (1)
[0] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\temp\chrome-uplo
ader\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
[0] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
[0] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)

[0] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal
/child_process.js:251:5)
[0] node-pre-gyp ERR! System Windows_NT 6.1.7601
[0] node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\temp\\c
hrome-uploader\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "-
-fallback-to-build"
[0] node-pre-gyp ERR! cwd C:\temp\chrome-uploader\app\node_modules\usb
[0] node-pre-gyp ERR! node -v v10.13.0
[0] node-pre-gyp ERR! node-pre-gyp -v v0.10.3
[0] node-pre-gyp ERR! not ok
[0] npm WARN tidepool-uploader@2.8.4 No repository field.
[0]
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! usb@1.3.2 install: `node-pre-gyp install --fallback-to-build`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the usb@1.3.2 install script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional
 logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     C:\Users\patrik\AppData\Roaming\npm-cache\_logs\2018-11-17T08_1
4_20_120Z-debug.log
[0]
[0]     at ChildProcess.childProcess.once.code (C:\temp\chrome-uploader\node_mod
ules\builder-util\src\util.ts:254:14)
[0]     at Object.onceWrapper (events.js:273:13)
[0]     at ChildProcess.emit (events.js:182:13)
[0]     at maybeClose (internal/child_process.js:962:16)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

[0] From previous event:
[0]     at installOrRebuild (C:\temp\chrome-uploader\node_modules\app-builder-li
b\out\util\yarn.js:68:17)
[0]     at C:\temp\chrome-uploader\node_modules\electron-builder\src\cli\install
-app-deps.ts:56:9
[0]     at Generator.next (<anonymous>)
[0] From previous event:
[0]     at installAppDeps (C:\temp\chrome-uploader\node_modules\electron-builder
\out\cli\install-app-deps.js:174:17)
[0]     at then (C:\temp\chrome-uploader\node_modules\electron-builder\src\cli\c
li.ts:42:48)
[0]     at runCallback (timers.js:705:18)
[0]     at tryOnImmediate (timers.js:676:5)
[0]     at processImmediate (timers.js:658:5)
[0] From previous event:
[0]     at Object.args [as handler] (C:\temp\chrome-uploader\node_modules\electr
on-builder\src\cli\cli.ts:42:48)
[0]     at Object.runCommand (C:\temp\chrome-uploader\node_modules\yargs\lib\com
mand.js:238:44)
[0]     at Object.parseArgs [as _parseArgs] (C:\temp\chrome-uploader\node_module
s\yargs\yargs.js:1059:30)
[0]     at Object.get [as argv] (C:\temp\chrome-uploader\node_modules\yargs\yarg
s.js:1000:21)
[0]     at Object.<anonymous> (C:\temp\chrome-uploader\node_modules\electron-bui
lder\src\cli\cli.ts:25:28)
[0]     at Module._compile (internal/modules/cjs/loader.js:688:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)

[0]     at Module.load (internal/modules/cjs/loader.js:598:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
[0]     at startup (internal/bootstrap/node.js:285:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[0] electron-builder install-app-deps exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tidepool-uploader@2.8.4 postinstall: `concurrently "electron-builder in
stall-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js packag
e.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tidepool-uploader@2.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\patrik\AppData\Roaming\npm-cache\_logs\2018-11-17T08_14_20
_261Z-debug.log

C:\temp\chrome-uploader>

**Comment by gniezen** [comment]
Hi @usko1 ! I've experienced similar issues with the node-usb dependency. For Node 10, try building with v10.1.0. For the current version of Electron that we're using (1.8.4), it's best to build with Node v8.2.1. We will be switching to v10.1.0 when we update Electron to v3 in the next couple of weeks.
